### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by DanteAndroid** [githubwing/GankClient-Kotlin#1]
1. Kotlin 会影响 app 兼容性吗？
1. 会影响 AS 的功能或者插件的功能吗？
1. 既然这么好用，为什么 Google 不推广？

**Comment by Lsy1992** [comment]
只是换种写法而已··

**Comment by ghost** [comment]
需要装啥其他的东西吗,demo跑起来,代码里面不能互相跳转
