### ISSUE TITLE
关于Dagger2的问题

### ISSUE THREAD

**Issue by LomoLin** [githubwing/GankClient-Kotlin#19]
为什么在App.kt中的ApiComponent对象也是用Inject注解呢，我这边看不懂，本身也还在看Dagger2的东西，所以麻烦知道下，谢谢！

**Comment by CodeK1988** [comment]
@LomoLin ext.kt的地方调用了

**Comment by LomoLin** [comment]
> @LomoLin ext.kt的地方调用了

谢谢
