### ISSUE TITLE
 app:load_image这个没看懂，ImageView有这个自定义属性？

### ISSUE THREAD

**Issue by vihuela** [githubwing/GankClient-Kotlin#6]
<ImageView
            android:scaleType="centerCrop"
            android:transitionName="img"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:load_image="@{url}" />

**Comment by SomnusWu** [comment]
这个是databing的知识 。

**Comment by vihuela** [comment]
> "@{url}" 是引用绑定的model中的属性懂啊，但是没懂图片加载的逻辑在哪里

**Comment by SomnusWu** [comment]
DataBindingAdapterUtil.kt

**Comment by vihuela** [comment]
多谢哥们

**Comment by SomnusWu** [comment]
我擦 等等  你运行起来了？

**Comment by vihuela** [comment]
。。。。。你没运行起来么？

**Comment by vihuela** [comment]
不用修改任何配置，然后导入时不用升级gradle配置，新版本的kotlin插件去除了extensions插件

**Comment by SomnusWu** [comment]
嗯  你放个apk  zip包

**Comment by vihuela** [comment]
不支持上传apk，改为zip，你改后缀为apk
[app-debug.zip](https://github.com/githubwing/GankClient-Kotlin/files/1079602/app-debug.zip)
