### ISSUE TITLE
dragger不是最新的吧

### ISSUE THREAD

**Issue by yanchunlan** [githubwing/GankClient-Kotlin#9]
最新的都是dragger2了，而且kotlin都没用ango,这算什么kotlin开发

**Comment by yanchunlan** [comment]
问题

**Comment by githubwing** [comment]
抱歉哈，麻烦看下在说话，确实是用的dagger2。

另外敢问ango是啥？

我听过anko,django, 不知道啥是ango. 

不用所谓的ango就不能算kotlin开发了吗？
